# Fine-grained personal access tokens
# Repository permissions:
#   Read access: actions, variables, metadata, secrets
#   Read and Write access: contents, commit statuses, issues, pull requests
# User permissions:
#   - none
name: Publish Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and publish package
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'

      - name: Install dependencies
        run: npm install
      - name: Ensure the integrity of packages from the public npm registry
        run: npm audit signatures

      - name: Build Vue 3 library
        run: npm run build
      - name: Build Storybook
        run: npm run build-storybook

      - name: Publish package
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          NPM_TOKEN: ${{ secrets.NPM }}
        run: npx semantic-release